##Title
This document summarizes exploration of storm and severe weather event data from the National Weather Service 
between 1950 and 2011.  The analysis ranks events that are most harmful with respect to population 
health and those that have the greatest economic consequences.

##Synopsis
asdf

### Data Processing
```{r DataProcessing, cached = TRUE}
setwd("~/Documents/r/coursera/5 Reproducible Research/assignment2")

if (!file.exists("repdata%2Fdata%2FStormData.csv.bz2")) {
    fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
    download.file(fileUrl, destfile = "repdata%2Fdata%2FStormData.csv.bz2", method = "curl")
}

storm <- read.csv("repdata%2Fdata%2FStormData.csv.bz2")
```

### Data Transformations
```{r DataTransformations}
library(dplyr)

#Attempt to normalize EVTYPE values
#Initial number of EVTYPE groupings
nrow(storm %>%
    group_by(EVTYPE) %>%
    summarize(counter = sum(STATE__)))

#Convert lower case EVTYPE values to upper case 
storm$EVTYPE <- toupper(storm$EVTYPE)
nrow(storm %>%
    group_by(EVTYPE) %>%
    summarize(counter = sum(STATE__)))

#Convert plural EVTYPE values to singular
storm$EVTYPE <- sub("S$", "", storm$EVTYPE)
nrow(storm %>%
    group_by(EVTYPE) %>%
    summarize(counter = sum(STATE__)))

#Add new column HARMFUL to store accumulated FATALITIES and INJURIES
storm$HARMFUL <- storm$FATALITIES + storm$INJURIES

#Function applyDamageExp takes damage amount and damage exponent as input to determine actual damage amount
applyDamageExp <- function (x, y) {
    if(x == "K") as.numeric(y) * 1000
    else if(x == "M") as.numeric(y) * 1000000
    else if (x == "B") as.numeric(y) * 1000000000
    else 0
}

#Add new column PROPDMGAMT to store actual property damage amount
storm$PROPDMGAMT <- apply(storm[, c('PROPDMGEXP', 'PROPDMG')], 1, 
                          function(x) applyDamageExp(x['PROPDMGEXP'], x['PROPDMG']))

#Add new column CROPDMGAMT to store actual crop damage amount
storm$CROPDMGAMT <- apply(storm[, c('CROPDMGEXP', 'CROPDMG')], 1, 
                          function(x) applyDamageExp(x['CROPDMGEXP'], x['CROPDMG']))

#Add new column DAMAGEAMT to store accumulated PROPDMGAMT and CROPDMGAMT
storm$DAMAGEAMT <- storm$PROPDMGAMT + storm$CROPDMGAMT
```

###Results
```{r results}
library(ggplot2)

#events that are most harmful with respect to population health
harmfulDF <- storm %>%
    group_by(EVTYPE) %>%
    summarize(counter = sum(HARMFUL)) %>%
    filter(counter > 0) %>%
    arrange(desc(counter))

harmfulDF

ggplot(harmfulDF) +
    geom_histogram(aes(x=counter), binwidth = 5000, col="red", fill="grey") +
    ggtitle("Count of the Number of People Harmed Per Severe Weather Event") +
    xlab("Harmful Count") +
    ylab("Number of Events")

#events that have the greatest economic consequences
damageDF <- storm %>%
    group_by(EVTYPE) %>%
    summarize(amt = sum(DAMAGEAMT)) %>%
    filter(amt > 0) %>%
    arrange(desc(amt))

damageDF

ggplot(damageDF) +
    geom_histogram(aes(x=amt/1000000), binwidth = 5000, col="red", fill="grey") +
    ggtitle("Accumulated Amount of Dollars of Damage Per Severe Weather Event") +
    xlab("Damage Amount (in millions)") +
    ylab("Number of Events")
```
